
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class MainMenu extends javax.swing.JFrame {

    private Clip musicClip;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
       playMusic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playbtn = new javax.swing.JButton();
        howToPlayBtn = new javax.swing.JButton();
        leaderboardBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        musicOnBtn = new javax.swing.JButton();
        musicOffBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(519, 907));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playbtn.setBackground(new java.awt.Color(0, 0, 0));
        playbtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        playbtn.setForeground(new java.awt.Color(255, 255, 255));
        playbtn.setText("Let's go!");
        playbtn.setFocusable(false);
        playbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playbtnMouseClicked(evt);
            }
        });
        playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtnActionPerformed(evt);
            }
        });
        getContentPane().add(playbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        howToPlayBtn.setBackground(new java.awt.Color(0, 0, 0));
        howToPlayBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        howToPlayBtn.setForeground(new java.awt.Color(255, 255, 255));
        howToPlayBtn.setText("Game Guide");
        howToPlayBtn.setFocusable(false);
        howToPlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(howToPlayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        leaderboardBtn.setBackground(new java.awt.Color(0, 0, 0));
        leaderboardBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        leaderboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        leaderboardBtn.setText("Leaderboard");
        leaderboardBtn.setFocusable(false);
        leaderboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(leaderboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        exitBtn.setBackground(new java.awt.Color(0, 0, 0));
        exitBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Quit");
        exitBtn.setFocusable(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SPACE SHUFFLE");
        jLabel8.setFocusable(false);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 380, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("SPACE SHUFFLE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 380, -1));

        musicOnBtn.setBackground(new java.awt.Color(255, 204, 204));
        musicOnBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        musicOnBtn.setForeground(new java.awt.Color(0, 0, 0));
        musicOnBtn.setText("Music on");
        musicOnBtn.setFocusable(false);
        musicOnBtn.setMargin(new java.awt.Insets(3, 14, 3, 14));
        musicOnBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        musicOnBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        musicOnBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        musicOnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicOnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(musicOnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 120, 40));

        musicOffBtn.setBackground(new java.awt.Color(255, 204, 204));
        musicOffBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        musicOffBtn.setForeground(new java.awt.Color(0, 0, 0));
        musicOffBtn.setText("Music off");
        musicOffBtn.setFocusable(false);
        musicOffBtn.setMargin(new java.awt.Insets(3, 14, 3, 14));
        musicOffBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        musicOffBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        musicOffBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        musicOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicOffBtnActionPerformed(evt);
            }
        });
        getContentPane().add(musicOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 520, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void leaderboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardBtnActionPerformed
stopMusic();
        dispose();
        new Leaderboard().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_leaderboardBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed

        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void playbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtnActionPerformed
  
        dispose();
        new StartWindow().setVisible(true);
    }//GEN-LAST:event_playbtnActionPerformed

    private void howToPlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayBtnActionPerformed
       stopMusic();
        new GameGuide().setVisible(true);
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_howToPlayBtnActionPerformed

    private void playbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playbtnMouseClicked

    }//GEN-LAST:event_playbtnMouseClicked

    private void musicOnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicOnBtnActionPerformed
        playMusic();        // TODO add your handling code here:
    }//GEN-LAST:event_musicOnBtnActionPerformed

    private void musicOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicOffBtnActionPerformed
        stopMusic();        // TODO add your handling code here:
    }//GEN-LAST:event_musicOffBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void playMusic() {
        stopMusic();
        try {
            
            File sound = new File("Audio/game.wav");
            musicClip = AudioSystem.getClip(); // Store the Clip instance
            musicClip.open(AudioSystem.getAudioInputStream(sound));
            musicClip.loop(Clip.LOOP_CONTINUOUSLY);
            musicClip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void stopMusic() {
        if (musicClip != null && musicClip.isRunning()) {
            musicClip.stop(); // Stop the music clip if it's running
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                MainMenu mainMenu= new MainMenu();
//                mainMenu.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton howToPlayBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton leaderboardBtn;
    private javax.swing.JButton musicOffBtn;
    private javax.swing.JButton musicOnBtn;
    private javax.swing.JButton playbtn;
    // End of variables declaration//GEN-END:variables
}
